name: "Building my First Resource"

# This step ensures that the GitHub Actions workflow will only run when code is pushed (commited) to branches that begin with feature/ or fix/
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  terraform:
    name: "Terraform Deploy"
    # This tells GitHub Actions to run this job on a virtual machine using the latest Ubuntu Linux runner.
    runs-on: ubuntu-latest

    # Uses the root directory (./) as the default location for commands
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setting up AWS CLI credentials for use in the workflow  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      # Optional: Terraform init with backend config
      - name: Terraform Init
        working-directory: ./
        run: |
          cd infra && terraform init -backend-config="bucket=ph-github-state" -backend-config="key=terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Plan
        run: cd infra && terraform plan
