name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      aws-assume-role-arn:
        type: string
        required: true
      aws-region:
        type: string
        required: true
      aws-statefile-s3-bucket:
        type: string
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate branch name
        id: check_branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          VALID_PREFIXES="feature/ fix/"
    
          for PREFIX in $VALID_PREFIXES; do
            if [[ "$BRANCH_NAME" == $PREFIX* ]]; then
              echo "Valid branch: $BRANCH_NAME"
              exit 0
            fi
          done

          echo "Invalid branch name '$BRANCH_NAME'. It must start with one of: $VALID_PREFIXES"
          exit 1  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Init
        run: |
          cd infra && terraform init \
            -backend-config="bucket=${{ inputs.aws-statefile-s3-bucket }}" \
            -backend-config="key=${{ github.event.repository.name }}" \
            -backend-config="region=${{ inputs.aws-region }}" \

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Plan
        id: terraform-plan
        run: cd infra &&
          terraform plan -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" -out="${{ inputs.environment }}.plan"

      - name: Get the branch name
        id: get_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      
      - name: Create a pull request for FEATURE
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated Pull Request"
          body: "This is an automatically generated pull request."
          base: dev  # The branch where the PR will be merged into
          head: ${{ env.BRANCH_NAME }}  # Dynamically use the current branch name  

